#include "Ultrasonic.h"
#include "Config.h"
void Ultrasonic::begin(uint8_t trigPin,uint8_t echoPin){_trigPin=trigPin;_echoPin=echoPin;pinMode(_trigPin,OUTPUT);pinMode(_echoPin,INPUT);digitalWrite(_trigPin,LOW);attachInterruptArg(digitalPinToInterrupt(_echoPin),&Ultrasonic::isrRouter,this,CHANGE);}
void Ultrasonic::setMaxDistance(float maxDistanceCm){_maxDistanceCm=constrain(maxDistanceCm,30.0f,400.0f);}
bool Ultrasonic::requestMeasurement(){if(_waiting)return false;noInterrupts();_echoRiseUs=0;_echoFallUs=0;_pulseReady=false;interrupts();_newResult=false;_waiting=true;digitalWrite(_trigPin,LOW);delayMicroseconds(2);digitalWrite(_trigPin,HIGH);delayMicroseconds(10);digitalWrite(_trigPin,LOW);_triggerAtUs=micros();return true;}
void IRAM_ATTR Ultrasonic::isrRouter(void* arg){static_cast<Ultrasonic*>(arg)->onEchoChange();}
void IRAM_ATTR Ultrasonic::onEchoChange(){if(!_waiting)return;const uint32_t now=micros();if(digitalRead(_echoPin)==HIGH)_echoRiseUs=now;else if(_echoRiseUs!=0){_echoFallUs=now;_pulseReady=true;}}
float Ultrasonic::filteredDistance(float value){_filter[_filterIndex]=value;_filterIndex=(_filterIndex+1)%Config::ULTRASONIC_FILTER_SIZE;if(_filterCount<Config::ULTRASONIC_FILTER_SIZE)++_filterCount;float sorted[Config::ULTRASONIC_FILTER_SIZE];for(uint8_t i=0;i<_filterCount;++i)sorted[i]=_filter[i];for(uint8_t i=0;i<_filterCount;++i)for(uint8_t j=i+1;j<_filterCount;++j)if(sorted[j]<sorted[i]){float t=sorted[i];sorted[i]=sorted[j];sorted[j]=t;}if(_filterCount<=2){float sum=0;for(uint8_t i=0;i<_filterCount;++i)sum+=sorted[i];return _filterCount?sum/_filterCount:value;}float sum=0;for(uint8_t i=1;i<_filterCount-1;++i)sum+=sorted[i];return sum/(_filterCount-2);}
void Ultrasonic::finishInvalid(){_waiting=false;_result.valid=false;_result.rawDistanceCm=-1;_result.distanceCm=-1;_result.timestampMs=millis();_newResult=true;}
void Ultrasonic::update(){if(!_waiting)return;bool ready=false;uint32_t rise=0,fall=0;noInterrupts();ready=_pulseReady;if(ready){rise=_echoRiseUs;fall=_echoFallUs;_pulseReady=false;}interrupts();if(ready){_waiting=false;const uint32_t pulseUs=fall-rise;const float raw=pulseUs*0.0343f*0.5f;_result.timestampMs=millis();_result.rawDistanceCm=raw;if(raw<Config::ULTRASONIC_MIN_CM||raw>_maxDistanceCm){_result.valid=false;_result.distanceCm=-1;}else{_result.valid=true;_result.distanceCm=filteredDistance(raw);}_newResult=true;return;}if(micros()-_triggerAtUs>=Config::ULTRASONIC_TIMEOUT_US)finishInvalid();}
UltrasonicResult Ultrasonic::consumeResult(){_newResult=false;return _result;}
