import { createHash, randomUUID } from "node:crypto";
import { createServer } from "node:http";
import Redis from "ioredis";
import { WebSocket, WebSocketServer } from "ws";
const INSTANCE_ID=randomUUID(), MAX_MESSAGE_BYTES=16*1024, rooms=new Map(), channelIndex=new Map(); let redisPub=null,redisSub=null;
if(process.env.REDIS_URL){redisPub=new Redis(process.env.REDIS_URL,{maxRetriesPerRequest:2,enableReadyCheck:true});redisSub=redisPub.duplicate();redisPub.on("error",e=>console.error("[redis:pub]",e.message));redisSub.on("error",e=>console.error("[redis:sub]",e.message));redisSub.on("message",(channel,raw)=>{const route=channelIndex.get(channel);if(!route)return;try{const env=JSON.parse(raw);if(env.origin===INSTANCE_ID||typeof env.payload!=="string")return;sendToSet(route.kind==="data"?route.room.viewers:route.room.devices,env.payload);}catch{}});}
function validIdentity(v,min){return typeof v==="string"&&v.length>=min&&v.length<=64&&/^[A-Za-z0-9._-]+$/.test(v);}function parseClient(req){const u=new URL(req.url??"/","http://localhost"),role=u.searchParams.get("role"),deviceId=u.searchParams.get("deviceId")??"",token=u.searchParams.get("token")??"";if(role!=="device"&&role!=="viewer")return{error:"role inválido"};if(!validIdentity(deviceId,3))return{error:"deviceId inválido"};if(!validIdentity(token,8))return{error:"token inválido"};return{role,deviceId,token};}function roomHash(id,token){return createHash("sha256").update(`${id}:${token}`).digest("hex").slice(0,32);}function getRoom(id,token){const h=roomHash(id,token);if(rooms.has(h))return rooms.get(h);const r={hash:h,deviceId:id,devices:new Set(),viewers:new Set(),dataChannel:`smart-radar:data:${h}`,commandChannel:`smart-radar:command:${h}`,onlineKey:`smart-radar:online:${h}`};rooms.set(h,r);channelIndex.set(r.dataChannel,{room:r,kind:"data"});channelIndex.set(r.commandChannel,{room:r,kind:"command"});if(redisSub)redisSub.subscribe(r.dataChannel,r.commandChannel).catch(e=>console.error(e.message));return r;}function sendJson(s,o){if(s.readyState===WebSocket.OPEN)s.send(JSON.stringify(o));}function sendToSet(set,p){for(const s of set)if(s.readyState===WebSocket.OPEN)s.send(p);}function allowed(role,p){if(!p||typeof p!=="object"||Array.isArray(p)||typeof p.type!=="string")return false;return role==="viewer"?["command","settings","ping"].includes(p.type):["radar","status","config","ack","error","csv_begin","csv_chunk","csv_end","device_hello","pong"].includes(p.type);}async function publish(channel,payload){if(!redisPub)return;try{await redisPub.publish(channel,JSON.stringify({origin:INSTANCE_ID,payload}));}catch(e){console.error(e.message);}}async function online(r,value){if(!redisPub)return;try{value?await redisPub.set(r.onlineKey,"1","EX",25):await redisPub.del(r.onlineKey);}catch{}}function announce(r,value){const p=JSON.stringify({type:"relay",status:"connected",deviceOnline:value,deviceId:r.deviceId,redisBackplane:Boolean(redisPub)});sendToSet(r.viewers,p);void publish(r.dataChannel,p);}
const server=createServer((req,res)=>{res.statusCode=426;res.setHeader("content-type","application/json; charset=utf-8");res.end(JSON.stringify({ok:false,message:"Use WebSocket em /api/ws."}));});const wss=new WebSocketServer({server});
wss.on("connection",(socket,request)=>{const client=parseClient(request);if(client.error){socket.close(1008,client.error);return;}const room=getRoom(client.deviceId,client.token),set=client.role==="device"?room.devices:room.viewers;set.add(socket);socket.isAlive=true;socket.on("pong",()=>socket.isAlive=true);if(client.role==="device"){void online(room,true);announce(room,true);}else if(redisPub)redisPub.get(room.onlineKey).then(v=>sendJson(socket,{type:"relay",status:"connected",deviceOnline:v==="1",deviceId:room.deviceId,redisBackplane:true})).catch(()=>{});else sendJson(socket,{type:"relay",status:"connected",deviceOnline:room.devices.size>0,deviceId:room.deviceId,redisBackplane:false});socket.on("message",(buffer,isBinary)=>{if(isBinary||!buffer.length||buffer.length>MAX_MESSAGE_BYTES){socket.close(1009,"mensagem inválida");return;}const payload=buffer.toString("utf8");let parsed;try{parsed=JSON.parse(payload);}catch{sendJson(socket,{type:"error",message:"JSON inválido."});return;}if(!allowed(client.role,parsed)){sendJson(socket,{type:"error",message:"Mensagem não permitida."});return;}if(client.role==="device"){sendToSet(room.viewers,payload);void publish(room.dataChannel,payload);void online(room,true);}else{sendToSet(room.devices,payload);void publish(room.commandChannel,payload);}});socket.on("close",()=>{set.delete(socket);if(client.role==="device"&&room.devices.size===0){void online(room,false);announce(room,false);}});});
const heartbeat=setInterval(()=>{for(const s of wss.clients){if(s.isAlive===false){s.terminate();continue;}s.isAlive=false;s.ping();}if(redisPub)for(const r of rooms.values())if(r.devices.size)void online(r,true);},20000);server.on("close",()=>clearInterval(heartbeat));export default server;
